# Generated by Django 5.2.14 on 2026-05-31 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('session_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('product_id', models.UUIDField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('cprp_category', models.CharField(blank=True, max_length=100, null=True)),
                ('cprp_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('cprp_price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('cprp_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('synced_to_cprp', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
